# Generated by Django 2.2.6 on 2020-07-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
