# Generated by Django 2.2.6 on 2020-07-06 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='#', max_length=10)),
                ('name', models.CharField(default='#', max_length=100)),
                ('email_id', models.CharField(default='#', max_length=40)),
                ('branch', models.CharField(default='#', max_length=4)),
                ('year', models.CharField(default='#', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
