# Generated by Django 2.2.6 on 2020-07-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(default='#', max_length=1),
        ),
    ]
